### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Mate2xo** [Mate2xo/Creeons_la_coop#94]
*en attente de la vidéo, contacter Jade*

Navbar
- [ ] faire un dropdown sur `en savoir plus`
- [x] remplacer la partie `se connecter` etc, par `espace membre`

Bandeau
- [x] rendre le bandeau fixe (1 image au lieu de 2 actuellement)
- [x] insérer la catch phrase
- [x] CTA `devenir membre` -> dirige vers `en savoir plus`

Contenu
- [ ] insérer la vidéo qui sera fournie prochainement

**Comment by fastndcurious** [comment]
On peut peut-être faire un seul bouton dropdown avec : 
- s'inscrire
- se connecter

P.S : j'attends ta vidéo pour faire ma PR de mes propositiions de modifs ?

**Comment by Mate2xo** [comment]
oauis on ne m'a toujours pas fourni de vidéo, donc pour l'instant on fera sans
Ok pour le dropdown, tu pourrais l'appeller `espace membre` (c'est le terme qu'ils voulaient)
