### ISSUE TITLE
En savoir plus

### ISSUE THREAD

**Issue by Mate2xo** [Mate2xo/Creeons_la_coop#95]
*En attente du formulaire d'inscription*

Partie Fonctionnement
- [x] Insérer le graphique de la charte de fonctionnement (ressource fournie)

Partie Comment Adhérer
- [x] Lien Hello Asso (20E)
- [ ] Formulaire à télécharger
- [x] Aller sur place (au magasin)
- [x] Nous soutenir

Charte des produits
- [x] Insérer la charte (ressource fournie)

**Comment by fastndcurious** [comment]
du coup tu veux la google map soit dans une rubrique seulement ?
Je la mettrais plutôt sur la landing dans une div en dessous de l'image, non ?

**Comment by Mate2xo** [comment]
La google map ne sera que dans la partie producteurs, oui. Je l'ai déjà supprimée de la partie Missions
